import "server-only";

/**
 * Turns discovered routes into Playwright specs.
 *
 * This is deliberately mechanical rather than clever. Every assertion is
 * something that is true of any working page - the route exists and was served,
 * it rendered a body, and a form that the source declares is present.
 * Nothing here guesses at business rules, because nothing here has read them.
 * A generated spec is a starting point a human edits, not a finished test.
 */

export type RouteInput = {
  path: string;
  title: string;
  forms: number;
  gated: boolean;
  risk: string | null;
};

export type GeneratedCase = {
  title: string;
  description: string;
  steps: string[];
  expectedResult: string;
  priority: "critical" | "high" | "medium" | "low";
  filePathHint: string;
  code: string;
};

/** A route reduced to something usable as an identifier. */
function slug(routePath: string): string {
  const cleaned = routePath
    .replace(/[[\]{}:]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
  return cleaned || "home";
}

/**
 * A dynamic segment has no value we can know, so it is filled with something
 * obviously placeholder. The spec is marked so nobody mistakes it for passing
 * against real data.
 */
function concreteUrl(routePath: string): { url: string; hasPlaceholder: boolean } {
  const hasPlaceholder = /\[|:/.test(routePath);
  const url = routePath
    .replace(/\[\.{3}([^\]]+)\]/g, "placeholder")
    .replace(/\[([^\]]+)\]/g, "placeholder")
    .replace(/:([A-Za-z0-9_]+)/g, "placeholder");
  return { url, hasPlaceholder };
}

function priorityFor(route: RouteInput): GeneratedCase["priority"] {
  if (route.risk === "critical") return "critical";
  if (route.risk === "high" || route.gated) return "high";
  if (route.path === "/") return "high";
  return route.risk === "medium" ? "medium" : "low";
}

export function generateSpecsForRoutes(routes: RouteInput[], baseUrl: string): GeneratedCase[] {
  const base = baseUrl.replace(/\/+$/, "");

  return routes.map((route) => {
    const { url, hasPlaceholder } = concreteUrl(route.path);
    const name = slug(route.path);
    const target = `${base}${url === "/" ? "/" : url}`;

    const notes = [
      hasPlaceholder
        ? "// This route has a dynamic segment. \"placeholder\" stands in for a real\n// id, so replace it with a value that exists before trusting this spec."
        : null,
      route.gated
        ? "// This route looks gated. Without a signed-in session it may redirect to\n// a sign-in page, which Playwright follows - so this checks the app served\n// something, not that the gated page itself was reached."
        : null,
    ].filter(Boolean);

    const body = [
      `  const response = await page.goto(${JSON.stringify(target)});`,
      "",
      "  // Redirects are followed before this is read, so a gated route that",
      "  // bounces to a sign-in page still reports the page it landed on.",
      "  // Below 400 means the route exists and was served: a 404 here says the",
      "  // base URL does not host this route, which is a real failure rather",
      "  // than something to wave through.",
      "  expect(response?.status() ?? 0).toBeLessThan(400);",
      "  await expect(page.locator('body')).toBeVisible();",
      route.forms > 0 && !route.gated
        ? "\n  // The source declares a form on this route.\n  await expect(page.locator('form').first()).toBeVisible();"
        : "",
    ]
      .filter(Boolean)
      .join("\n");

    const code = `import { test, expect } from "@playwright/test";

// Generated by Parikshan from the route ${route.path} found in the repository.
${notes.length ? notes.join("\n") + "\n" : ""}
test(${JSON.stringify(`${route.title || route.path} loads`)}, async ({ page }) => {
${body}
});
`;

    return {
      title: `${route.title || route.path} loads`,
      description: `Opens ${route.path} and checks the application responds and renders.`,
      steps: [
        `Navigate to ${route.path}`,
        "Check the route was served, following any redirect",
        "Check the page renders a body",
        ...(route.forms > 0 && !route.gated ? ["Check the form declared in the source is present"] : []),
      ],
      expectedResult: "The route exists at the base URL, is served without an error, and renders.",
      priority: priorityFor(route),
      filePathHint: `tests/parikshan/${name}.spec.ts`,
      code,
    };
  });
}
