/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTestSelectionRouteImport } from './routes/_app/test-selection'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects/new'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdCasesCaseIdRouteImport } from './routes/_app/projects/$projectId/cases/$caseId'
import { Route as AppProjectsProjectIdRunsIndexRouteImport } from './routes/_app/projects/$projectId/runs/index'
import { Route as AppProjectsProjectIdRunsRunIdRouteImport } from './routes/_app/projects/$projectId/runs/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTestSelectionRoute = AppTestSelectionRouteImport.update({
  id: '/test-selection',
  path: '/test-selection',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdCasesCaseIdRoute =
  AppProjectsProjectIdCasesCaseIdRouteImport.update({
    id: '/projects/$projectId/cases/$caseId',
    path: '/projects/$projectId/cases/$caseId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdRunsIndexRoute =
  AppProjectsProjectIdRunsIndexRouteImport.update({
    id: '/projects/$projectId/runs/',
    path: '/projects/$projectId/runs/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdRunsRunIdRoute =
  AppProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/projects/$projectId/runs/$runId',
    path: '/projects/$projectId/runs/$runId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/integrations': typeof AppIntegrationsRoute
  '/settings': typeof AppSettingsRoute
  '/test-selection': typeof AppTestSelectionRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/cases/$caseId': typeof AppProjectsProjectIdCasesCaseIdRoute
  '/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs/': typeof AppProjectsProjectIdRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/integrations': typeof AppIntegrationsRoute
  '/settings': typeof AppSettingsRoute
  '/test-selection': typeof AppTestSelectionRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/cases/$caseId': typeof AppProjectsProjectIdCasesCaseIdRoute
  '/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/runs': typeof AppProjectsProjectIdRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/test-selection': typeof AppTestSelectionRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/cases/$caseId': typeof AppProjectsProjectIdCasesCaseIdRoute
  '/_app/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/_app/projects/$projectId/runs/': typeof AppProjectsProjectIdRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/analytics'
    | '/dashboard'
    | '/integrations'
    | '/settings'
    | '/test-selection'
    | '/projects/new'
    | '/projects/'
    | '/projects/$projectId/'
    | '/projects/$projectId/cases/$caseId'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/analytics'
    | '/dashboard'
    | '/integrations'
    | '/settings'
    | '/test-selection'
    | '/projects/new'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/cases/$caseId'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/runs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/integrations'
    | '/_app/settings'
    | '/_app/test-selection'
    | '/_app/projects/new'
    | '/_app/projects/'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/cases/$caseId'
    | '/_app/projects/$projectId/runs/$runId'
    | '/_app/projects/$projectId/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/test-selection': {
      id: '/_app/test-selection'
      path: '/test-selection'
      fullPath: '/test-selection'
      preLoaderRoute: typeof AppTestSelectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/cases/$caseId': {
      id: '/_app/projects/$projectId/cases/$caseId'
      path: '/projects/$projectId/cases/$caseId'
      fullPath: '/projects/$projectId/cases/$caseId'
      preLoaderRoute: typeof AppProjectsProjectIdCasesCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/runs/': {
      id: '/_app/projects/$projectId/runs/'
      path: '/projects/$projectId/runs'
      fullPath: '/projects/$projectId/runs/'
      preLoaderRoute: typeof AppProjectsProjectIdRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/runs/$runId': {
      id: '/_app/projects/$projectId/runs/$runId'
      path: '/projects/$projectId/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof AppProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTestSelectionRoute: typeof AppTestSelectionRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdCasesCaseIdRoute: typeof AppProjectsProjectIdCasesCaseIdRoute
  AppProjectsProjectIdRunsRunIdRoute: typeof AppProjectsProjectIdRunsRunIdRoute
  AppProjectsProjectIdRunsIndexRoute: typeof AppProjectsProjectIdRunsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTestSelectionRoute: AppTestSelectionRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdCasesCaseIdRoute: AppProjectsProjectIdCasesCaseIdRoute,
  AppProjectsProjectIdRunsRunIdRoute: AppProjectsProjectIdRunsRunIdRoute,
  AppProjectsProjectIdRunsIndexRoute: AppProjectsProjectIdRunsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
