import { NextResponse } from "next/server";

import { currentUserId } from "@/lib/auth";
import { decryptToken } from "@/lib/crypto";
import { exportSpecsToRepo, repoFullName } from "@/lib/github";
import { getGithubConnection, listExecutableCases, resolveProject } from "@/db/queries";

/** Slugs a test name into a filename that is safe on every platform. */
function specFileName(name: string, id: string) {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60);
  return `tests/parikshan/${slug || id}.spec.ts`;
}

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const userId = await currentUserId();

  const project = await resolveProject(userId, id);
  if (!project) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const conn = await getGithubConnection(userId);
  if (!conn) return NextResponse.json({ error: "Connect GitHub first, on the Integrations page." }, { status: 409 });

  const fullName = repoFullName(project.githubRepoUrl);
  if (!fullName) {
    return NextResponse.json(
      { error: "This project has no GitHub repository URL. Add one in project settings." },
      { status: 409 },
    );
  }

  const cases = await listExecutableCases(userId, project.id);
  if (cases.length === 0) {
    return NextResponse.json({ error: "No test case has Playwright code to export." }, { status: 409 });
  }

  // Deduplicate: two cases can slug to the same filename, and the second PUT
  // would otherwise overwrite the first with no warning.
  const used = new Set<string>();
  const files = cases.map((c) => {
    let path = specFileName(c.name, c.id);
    if (used.has(path)) path = path.replace(/\.spec\.ts$/, `-${c.id.slice(0, 8)}.spec.ts`);
    used.add(path);
    return { path, content: c.code as string };
  });

  // Timestamped so repeated exports do not collide on an existing branch.
  const branch = `parikshan/specs-${Date.now()}`;

  try {
    const result = await exportSpecsToRepo(decryptToken(conn.accessTokenEncrypted), fullName, files, {
      branch,
      title: `Add ${files.length} Parikshan spec${files.length === 1 ? "" : "s"}`,
      body: `Generated by Parikshan for **${project.name}**.\n\n${files.map((f) => `- \`${f.path}\``).join("\n")}`,
    });
    return NextResponse.json({ ...result, repo: fullName });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Export failed." },
      { status: 502 },
    );
  }
}
